### PR TITLE
Feature show logs link

### PR DESCRIPTION
**Pull request by MMulthaupt**
Depends on #71

### CODE REVIEW

**Comment by MMulthaupt** [comment]
This change [has](https://github.com/andlabs/libui/issues/472) [problems](https://github.com/andlabs/ui/issues/370).

**Comment by MMulthaupt** [comment]
There is also no way to set a size strategy for controls with the current UI library. The layouting has no awareness of a control's ideal, minimum and maximum size. As a consequence, the link label takes up extra width and height, making it clickable in places where one wouldn't expect.

**Comment by dragetd** [comment]
Being clickable in more areas or not highlighting when moused over is really a minor and irrelevant thing.

I am a bit more annoyed at the amount of code needed inside trivrost, but eh, nothing we could do about it with this lib. Other than that, LGTM.

**Comment by dragetd** [comment]
You cleared up some error messages… should we mention such things in the changelog?

**Pull request merged**
