### PR TITLE
Documentation extend file locations

### PR DESCRIPTION
**Pull request by ma-assbrock**
Add a hint on the `--roaming` parameter in the documentation on the file locations.

### CODE REVIEW

**Comment by dragetd** [comment]
Eventho Github markdown support HTML tags, do we really want these in the text files? I'd prefer just a new line, which will force a linebreak.

**Comment by MMulthaupt** [comment]
The problem with the line breaks is there are too many markdown standards. E.g. removing the trailing whitespaces removes the line break in the Markdown preview of my IDE. The real solution is to move to something which is centrally standardized.

**Comment by dragetd** [comment]
Pandoc's markdown (https://pandoc.org/MANUAL.html#pandocs-markdown) is pretty common and also close to the well-speced GitHub markdown (https://github.github.com/gfm/)

I do not see why this invalidates my suggestion to not use HTML, to be honest.

But if we want something with less flavors, there is AsciiDoc.

**Comment by dragetd** [comment]
And if we use HTML, then at least XHTML compatible linebreaks in the form of `<br />` :-)

But I'd leave them completely out and stick to markdown. If not, then `<br />`, if not, then merge right away. @ma-assbrock your call!

**Pull request merged**
